### ISSUE TITLE
Interactive plots stopped working with new release

### ISSUE THREAD

**Issue by bmichanderson** [REditorSupport/vscode-R#810] opened 2021-10-06 08:52 UTC
**Describe the bug**
When I attach an R session in VSCode and use an interactive plot, the plotting window shows a blank white display. When I downgrade to release 2.2.0, the plotting window works as expected.

**To Reproduce**

1. Attach an interactive R terminal
2. Plot using e.g. plotly

## Do you want to fix by self? (We hope your help!)

No

**Expected behavior**
Interactive plotting produces a plot in a VSCode tab.

**Screenshots**
![image](https://user-images.githubusercontent.com/45042580/136171055-2f24a765-57f2-4f1e-b0c5-2b6695c2c0c9.png)

**Environment (please complete the following information):**

- OS: Windows 10 running WSL2 Ubuntu 20.04
- VSCode Version: 1.60.2
- R Version: 4.1.1
- vscode-R version: 2.3.0

**Comment by renkun-ken** [comment] 2021-10-06 11:52
Duplicate of #808.

**Closed by renkun-ken** 2021-10-06 11:52 UTC
Labels: bug
