### ISSUE TITLE
global Environment variables are abnormal

### ISSUE THREAD

**Issue by kongdd** [REditorSupport/vscode-R#1252] opened 2022-11-07 03:50 UTC
![image](https://user-images.githubusercontent.com/9815742/200222730-9b89345f-af7c-4293-8c15-7dfcc215c0e0.png)

**Comment by renkun-ken** [comment] 2022-11-07 11:49
Duplicate of #1229

**Closed by renkun-ken** 2022-11-07 11:49 UTC
Labels: bug

**Comment by kongdd** [comment] 2022-11-07 12:16
thank u
