### ISSUE TITLE
Unable to view plotly plots 

### ISSUE THREAD

**Issue by sunnyjones5** [REditorSupport/vscode-R#808] opened 2021-09-30 23:45 UTC
Up until recently I was able to generate and run plotly plots in the directly in Viewer but now whenever I do so it just comes up as blank with no readily identifiable error. I thought it might have been due to some packages I installed recently but I uninstalled R and all the packages and then reinstalled the bare minimum that I needed and I am still getting this issue even with the demo code from plotly. All I get is a blank white square and I am at a loss as to how to fix it. 

![image](https://user-images.githubusercontent.com/33134524/135544865-b8bab8a1-e542-4f22-beaa-661a50553dad.png)

(for the screenshot I just tacked the lines on to the end of a different script but I only ran the 3 visible lines)

**Environment:**

- OS:  Ubuntu 20.04.2 LTS but using Remote-SSH from a Mac Darwin 20.4.0
- VSCode Version: 1.60.2
- R Version: 4.1.1
- vscode-R version: 2.3.0

**Comment by renkun-ken** [comment] 2021-10-01 00:49
It was caused by #771 and fixed via #805. Please try the [latest development build](https://github.com/REditorSupport/vscode-R/releases/tag/latest).

**Closed by renkun-ken** 2021-10-01 00:49 UTC
Labels: bug

**Comment by sunnyjones5** [comment] 2021-10-01 01:12
This worked thank you so much!!!!
