### ISSUE TITLE
Cannot use R Help in VSCode-R with separately installed packages

### ISSUE THREAD

**Issue by jimjam-slam** [REditorSupport/vscode-R#853] opened 2021-11-03 01:13 UTC
**Describe the bug**
Searching for help on a function or package using either `?package::function` in the terminal, or using the "Open Help Topic using `?`" option on the sidebar, results in an R Help tab opening that contains:

```
httpd error
No package named [X] could be found
```

(Where `[X]` is the name of the package requested, or containing the function requested.)

This occurs for separately installed packages, but packages installed with R, like `base` or `stats`, work fine. This also doesn't affect hover help, which works as expected even for separately installed packages.

**To Reproduce**

1. Open an R terminal by either highlighting R code and hitting Cmd+Enter, or by running "R: Create R terminal" from the command palette
2. Type `?stats::lm` and observe help correctly opening
3. Install `ggplot2` using `install.packages("ggplot2")`
4. Type `?ggplot2::ggplot` and observe that help returns and httpd error
5. Select "Open Help Topic using `?`" from the R extension sidebar and type `ggplot2::ggplot`. Observe that help stil lreturns an error.
6. Select "Help Topics by package" from the R extensio nsidebar and note that only packages installed with R are listed.

## Do you want to fix by self? (We hope your help!)

Happy to help!

## (If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)

(If related)setting.json

```json
// R path for Linux
"r.rterm.linux": "/usr/bin/R"

# other `r.term` options not configured
```

**Expected behavior**
I expected help topic content to appear for separately installed packages, as it does for base packages.

**Screenshots**
![Screen Shot 2021-11-03 at 12 08 59](https://user-images.githubusercontent.com/6520659/139980331-f8215e07-5481-40b0-a619-25e32aa1ce3e.png)

![Screen Shot 2021-11-03 at 12 09 21](https://user-images.githubusercontent.com/6520659/139980567-7d1986b4-244a-46e6-baff-81e4568b3a79.png)

**Environment (please complete the following information):**

- OS: macOS 12.0.1
- VSCode Version: 1.61.2
- R Version: 4.1.2
- vscode-R version: 2.3.2

**Additional context**

Location of library containing packages that don't appear: `/Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library`. These packages can be still be loaded and used in R.

**Comment by renkun-ken** [comment] 2021-11-03 01:53
Does this help?

<img width="514" alt="image" src="https://user-images.githubusercontent.com/4662568/139999989-7c95586b-c647-47c5-94e3-22e9ee852749.png">

**Comment by renkun-ken** [comment] 2021-11-03 01:59
@ManuelHentschel I'm wondering if we could make `helpServer.R` auto-detect new packages added to the library and auto restart the help server accordingly?

**Comment by jimjam-slam** [comment] 2021-11-03 02:03
> Does this help?
> 
> <img alt="image" width="514" src="https://user-images.githubusercontent.com/4662568/139999989-7c95586b-c647-47c5-94e3-22e9ee852749.png">

Ahh yup, that did it! Thanks!

**Comment by renkun-ken** [comment] 2021-11-03 03:32
Duplicate of #661

**Closed by renkun-ken** 2021-11-03 03:32 UTC
Labels: bug
