### ISSUE TITLE
[chooseTerminal] issue

### ISSUE THREAD

**Issue by NoahsArk36** [REditorSupport/vscode-R#903] opened 2021-12-06 10:48 UTC
**Describe the bug**
My VSCode had been buggy after I installed Radian, every time I open VSCode and use run resource, it will prompt "Error identifying terminal".  This is what it says:

```jsonc
[chooseTerminal] A. There are 2 terminals: Terminal 0: powershell Terminal 1: radian B. There are 2 terminals: Terminal 0: powershell Terminal 1: radian C. There are 2 terminals: Terminal 0: powershell Terminal 1: radian 
```

**Environment (please complete the following information):**

- OS: Windows
- VSCode Version: 1.62.3
- R Version: 4.1.0
- vscode-R version: 2.3.4

**Additional context**

**Comment by renkun-ken** [comment] 2021-12-08 04:27
Duplicate of #899

**Closed by renkun-ken** 2021-12-08 04:27 UTC
Labels: bug
