### ISSUE TITLE
Show all plots created within a loop

### ISSUE THREAD

**Issue by dfriend21** [REditorSupport/vscode-R#538] opened 2021-01-26 17:43 UTC
**Is your feature request related to a problem? Please describe.**
This issue was mentioned in #181 (under known limitations, first bullet), but I thought I'd make it a feature request. I often use a for loop to iteratively cycle through a series of plots, and I use `readlines()` in the loop so that I can just press 'Enter' to look at the next plot. For example:

```
for(i in 1:10){
  plot(1,1,main=i) # make the plot
  input = readline("") # make the for loop stop until Enter is pressed
  if(input == "q"){ # quit if input is 'q'
    break;
  }
}
```
I just switched to using VSCode after using RStudio for several years - in RStudio, each plot shows up immediately in the plot window, rather than after the for loop is done. However, with the VSCode R extension, nothing is plotted until the for loop is done, and then it only shows the last plot. In addition, the plot history only has the last plot.

**Describe the solution you'd like**
It'd be nice if each plot was shown in each iteration - i.e. one plot would show up, and then when I press "Enter", the next plot would immediately show up in the plot pane.

**Describe alternatives you've considered**
Alternatively, having each plot saved to the plot history would also work - then I could just flip through them after the code has run.

**Comment by renkun-ken** [comment] 2021-02-06 16:52
Duplicate of #543.

I'd suggest that you use [httpgd](https://github.com/nx10/httpgd) as your default graphics device as I mentioned in https://github.com/Ikuyadeu/vscode-R/issues/543#issuecomment-771303291.

**Closed** 2021-07-19 08:28 UTC
Labels: feature-request, wontfix
