### ISSUE TITLE
PNG Plot window view does not refresh

### ISSUE THREAD

**Issue by fedxa** [REditorSupport/vscode-R#986] opened 2022-02-09 18:04 UTC
**Describe the bug**

The plot window does not refresh when new plot is generated. However, if the plot.png viewer is closed, generation of the new plot opens it again with new plot.

**To Reproduce**

Start R terminal.

Create a plot, e.g. `curve(sin,0,10)`. The plot.png view panel appears.

Issue new plot command, e.g. `curve(cos,0,10)` -- nothing changes.

I use the default potting, not httpgd.

**Comment by cjmathy** [comment] 2022-02-11 01:42
Same bug here. Tried rolling back to vscode-R versions 2.3.6 and 2.2.0, with no improvement.

OS: Mac OS Monterey
VSCode Version: 1.64.1
R Version: 4.0.3
vscode-R version: 2.3.8

**Comment by endlessbeloved** [comment] 2022-02-11 02:05
Same bug here.
os: LInux 
VSCode Version: 1.64.1
R Version: 4.0.5
vscode-R version: 2.3.8

**Comment by renkun-ken** [comment] 2022-02-11 02:44
I could reproduce it. Looks like it should be an upstream issue where vscode does not refresh editor tab on file changes in the recent releases.

**Comment by renkun-ken** [comment] 2022-02-17 15:56
Reported as an upstream issue https://github.com/microsoft/vscode/issues/143291.

**Comment by renkun-ken** [comment] 2022-02-23 00:44
Fixed upstream. Should be working in a recent insider and the next release.

**Comment by cjmathy** [comment] 2022-02-23 01:00
Thanks, @renkun-ken, for following up with the vscode team and for your fantastic extension!!

**Comment by renkun-ken** [comment] 2022-02-24 01:58
The fix is already included in the latest vscode insider.

**Comment by renkun-ken** [comment] 2022-04-10 12:01
Fixed in the latest release.

**Closed by renkun-ken** 2022-04-10 12:01 UTC
Labels: bug
