### ISSUE TITLE
Executing multi-line statement from second line onwards sends only one line to the terminal

### ISSUE THREAD

**Issue by david-cortes** [REditorSupport/vscode-R#1172] opened 2022-08-07 10:25 UTC
**Steps to reproduce:**
* Create an R file and write some multi-line statement on it, such as this:
```r
df <- data.frame(
    col1 = 1:10,
    col2 = 1:10
)
```
* Press Ctrl + Shift + P and select `R: Create R terminal`.
* Click on the second or third line of the multi-line statement in the R file so as to put the focus there.
* Press Ctrl + Enter.

**Expected behavior:** should send the whole multi-line statement to the R console (like RStudio does).

**Actual behavior:** sends only the line that was on focus, unless it was the first line of the statement.

**Comment by eitsupi** [comment] 2022-08-07 11:03
duplicate of #437

**Comment by andycraig** [comment] 2022-08-11 02:01
Yep, it's the bug linked by @eitsupi. Closing as duplicate.

**Closed by andycraig** 2022-08-11 02:01 UTC
Labels: bug
