### ISSUE TITLE
Terminal crashes with code: 3221225477 

### ISSUE THREAD

**Issue by ajinkya-k** [REditorSupport/vscode-R#1176] opened 2022-08-14 16:30 UTC
Type: <b>Bug</b>

Error message: "The terminal process "C:\Program Files\R\R-4.2.1\bin\x64\R.exe" terminated with exit code: 3221225477. "

Occurs when using R Interactive terminal to run commands. 

Issues #91044 and #94499 are not applicable because I am using 64bit VSCode on Windows 11, but the aforementioned issue threads are relevant only for 32bit installations. 

EDIT: typo

Extension version: 2.5.2
VS Code version: Code 1.70.1 (6d9b74a70ca9c7733b29f0456fd8195364076dda, 2022-08-10T06:08:33.642Z)
OS version: Windows_NT x64 10.0.22000
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (4.26GB free)|
|Process Argv|--crash-reporter-id e96a925a-10fe-40fe-b19c-4a75fdd0ee2c|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by gowerc** [comment] 2022-08-19 09:18
Does the R terminal work in vscode when you use it  yourself ?

**Comment by ajinkya-k** [comment] 2022-08-19 16:18
The crash occurs when using the R terminal interactively. I have been using Rstudio since the past few days and the R terminal doesn't crash when using it. So its only an issue when using it in VSCode

**Comment by gowerc** [comment] 2022-08-19 17:25
Does it crash if you load R from terminal / powershell  (not from within vscode) ?

**Comment by ajinkya-k** [comment] 2022-09-12 16:29
There is no console crash in Rstudio, it doesn't seem to crash when using it via Powershell on VSCode. 
When it does crash when using the "R-terminal" it briefly gives a message about running out of memory, but I have tracked memory usage and there doesn't seem to be an overuse of memory.

**Comment by ajinkya-k** [comment] 2022-10-10 15:27
I keep observing this behavior when using the `R - terminal` but not when running `R` in a powershell terminal.

**Comment by ajinkya-k** [comment] 2022-11-01 14:20
Okay I have more information. I had to clean install windows because of some OS driver issues, and this issue resurfaced. The most frequent cause of this issue is trying to use tab completion in R Terminal on VS Code. Is this perhaps caused by me installing the R Tools extension? As soon as I got a warning from VSCode saying R Tools and vscode-R might have conflicts I deleted it, but the crashing persists.

**Comment by albertosantini** [comment] 2022-11-27 08:57
Hey. Hope this helps.

https://blog.r-project.org/2022/11/01/sporadic-rterm-crashes-with-completion/index.html

**Comment by ajinkya-k** [comment] 2022-12-02 05:22
@albertosantini Thanks!
Just one question: there is no R-4.2.3 on the devel download channel. Perhaps you meant R-4.3.0 ?

**Comment by albertosantini** [comment] 2022-12-02 07:44
Yep, I suppose Tomas Kalibera, the author of that post, intended the "next" version.
Indeed it seems the next one, "eventually" will be 4.3.0.
https://cran.r-project.org/bin/windows/base/rdevel.html

Anyway I hope they fixed this annoying bug (and very difficult to track). 
It happens to me a few times and it is not nice when the terminal crashes in the middle of a session after a long setup of your data. ;)

**Comment by albertosantini** [comment] 2023-03-17 19:02
Sigh. Upgraded to 4.2.3, but after a command completion 
<img width="305" alt="image" src="https://user-images.githubusercontent.com/328179/225994962-d9e8fcc9-9cb6-454d-b973-631bc0dc8a45.png">

Checking if 4.2.3 contains the changes described in blog post above or maybe postponed.

**Comment by albertosantini** [comment] 2023-03-17 19:43
Bah... In NEWS I don't read any note about fixing the completion for 4.2.3. Sigh.

**Comment by albertosantini** [comment] 2023-03-17 21:55
It seems the changes are still in R-devel:
https://stat.ethz.ch/R-manual/R-devel/doc/html/NEWS.html

See: `Sporadic crashes of Rterm when using completion have been fixed.`

**Comment by albertosantini** [comment] 2023-03-30 15:51
[R version 4.3.0 (Already Tomorrow) prerelease versions](http://cran.r-project.org/src/base-prerelease) will appear starting Tuesday 2023-03-21. Final release is scheduled for Friday 2023-04-21.

Confirmed that `Sporadic crashes...` ^

**Comment by renkun-ken** [comment] 2023-04-25 08:51
Thanks for confirming. Closing.

**Closed by renkun-ken** 2023-04-25 08:51 UTC
