### ISSUE TITLE
httpgd plot viewer fail in remote server

### ISSUE THREAD

**Issue by QiangShiPKU** [REditorSupport/vscode-R#947] opened 2022-01-19 09:43 UTC
**Describe the bug**
When I press 'Enter & Command', R code can be run in R terminal. However, when I try plotting, httpgd plot viewer can open, showing "Status: 404 Reason: Not Found". By clicking "Open in External Browser" button, I can see the plot.

**To Reproduce**
see above and screenshot

## Do you want to fix by self? (We hope your help!)

No

(If related)setting.json

```jsonc
{
    "r.rterm.option": [
        "--r-binary=/raid1/shiq/app/miniconda3/envs/R/bin/R"
    ],
    "r.rpath.linux": "/raid1/shiq/app/miniconda3/envs/R/bin/R",
    "r.rterm.linux": "/raid1/shiq/app/miniconda3/envs/R/bin/radian",
    "r.bracketedPaste": true,
    "editor.hover.enabled": false,
    "r.plot.useHttpgd": true
}
```

**Expected behavior**
httpgd plot viewer can show plot normally

**Screenshots**
<img width="1364" alt="截屏2022-01-19 下午5 13 32" src="https://user-images.githubusercontent.com/40571792/150104148-ddf63653-c187-4af7-9d41-e184b8ade0e9.png">

**Environment (please complete the following information):**

- OS: Ubuntu 18.04.2
- VSCode Version: 1.63.2
- R Version: 4.1.1
- vscode-R version: 2.3.6

**Additional context**
No

**Comment by eitsupi** [comment] 2022-01-19 09:45
May be duplicate of #916, #923.

Please try update the httpgd package.

**Comment by renkun-ken** [comment] 2022-01-19 09:53
Yes, installing the latest release of httpgd should resolve this.

**Comment by QiangShiPKU** [comment] 2022-01-19 10:23
> Yes, installing the latest release of httpgd should resolve this.

Thanks a lot for your quick reply

**Closed** 2022-01-19 11:14 UTC
Labels: bug
