### ISSUE TITLE
Plot window doesn't update

### ISSUE THREAD

**Issue by hongooi73** [REditorSupport/vscode-R#1007] opened 2022-02-19 03:00 UTC
I'm using the latest version of the extension, updated on 8 Feb, along with Radian.

When I call `plot()` multiple times, the plotting window doesn't refresh. The only way to see a new plot is to close the existing window.

Steps to reproduce:

1. Run `plot(1,2)` in the R terminal. The plot should appear.
2. Run `plot(1:2,3:4)`. The plot stays the same.

Is this a bug? I notice that the plotting window has the path to a file in it ("c:\\tmp\\Rtmp*****\\vscode-R\\plot.png"), so I'm guessing the file hasn't been changed.

**Comment by Yunuuuu** [comment] 2022-02-19 04:03
check this https://github.com/REditorSupport/vscode-R/issues/986

**Comment by renkun-ken** [comment] 2022-02-19 04:16
Duplicate of #986

**Closed by renkun-ken** 2022-02-19 04:16 UTC
Labels: bug
