### ISSUE TITLE
Plot not rendered correctly when using `abline` in combination with `layout`

### ISSUE THREAD

**Issue by mihaiconstantin** [REditorSupport/vscode-R#1114] opened 2022-05-26 12:52 UTC
**Description**

Not sure if I am missing something here, but it seems that the plot rendering is not working as expected when creating a new plot after `abline` in the context of a custom `layout`.

**Reproduction**

To reproduce, please run the following code:

```r
# Seed.
set.seed(123)

# Data.
x <- rnorm(100)
y <- rnorm(100)
y_cumulative <- cumsum(y)

# Set layout.
layout(matrix(1:2, 2, 1))

# Plot daily downloads.
plot(x, y)
abline(h = mean(x))

# Plot cumulative downloads.
plot(x, y_cumulative)

# Reset layout.
layout(1:1)
```

![plot_issue](https://user-images.githubusercontent.com/20051042/170490647-c07c5d62-9b40-4b66-a91b-70744f53df1b.png)

It seems that swapping the order of the plots produces the expected output, i.e.:

```r
# Set layout.
layout(matrix(1:2, 2, 1))

# Plot cumulative downloads.
plot(x, y_cumulative)

# Plot daily downloads.
plot(x, y)
abline(h = mean(x))

# Reset layout.
layout(1:1)
```

![plot](https://user-images.githubusercontent.com/20051042/170492011-94369940-2f32-4999-9bad-a5e3da97ee1d.png)

**Environment (please complete the following information):**

- OS: macOS
- VSCode Version: 1.67.2
- R Version: 4.1.2
- vscode-R version: 2.5.0
- httpgd version: 1.3.0

**Comment by renkun-ken** [comment] 2022-05-27 00:43
@nx10 any idea?

**Comment by nx10** [comment] 2022-05-27 20:09
@mihaiconstantin Thanks for reporting this (and @renkun-ken thanks for the ping). I can confirm this is a bug in httpgd. It seems to be an issue with clipping. I will investigate.

**Comment by nx10** [comment] 2022-05-28 22:26
Should be fixed now: https://github.com/nx10/httpgd/commit/ba471a11dd546ca1ab06381deb9acbef89dcad36

**Comment by gowerc** [comment] 2022-08-13 15:25
@renkun-ken , I think we can close this now then

**Closed** 2022-08-14 01:25 UTC
Labels: bug
