### ISSUE TITLE
the `Run Line` command  sends only the lines inside the brackets

### ISSUE THREAD

**Issue by eitsupi** [REditorSupport/vscode-R#928] opened 2021-12-29 09:46 UTC
**Describe the bug**

I don't know if this is a bug or intended behavior.

When executing the Run Line command with the cursor inside the brackets `()` in a multi-line code, only the inside of the brackets will be sent to the terminal and the intended result will not be achieved.

![runline_in_bracket](https://user-images.githubusercontent.com/50911393/147648139-c6a639e2-ad0f-4636-971d-fd596c9a8a02.gif)

**To Reproduce**

```R
`+`(
  1,
  1
)
```

Execute the Run Line command with the cursor on the second or third line of the above code.
Then only `1,1` will be sent to the terminal and an error will be displayed.

(If related)setting.json

```jsonc
"r.bracketedPaste": true
```

**Expected behavior**

It would be great if the entire sequence of codes could be sent to the terminal.
RStudio seems work that way.

**Environment :**

- OS: Windows + Remote Ubuntu (Docker Container)
- VSCode Version: 1.63.2
- R Version: 4.1.2
- vscode-R version: 2.3.5

**Comment by andycraig** [comment] 2021-12-30 07:39
It's a bug. Duplicate of #437.

**Closed by andycraig** 2021-12-30 07:39 UTC
Labels: bug
