### ISSUE TITLE
Unable to read in large Excel file (~88,000 Kb) with read_xlsx. 

### ISSUE THREAD

**Issue by bwactkinson** [REditorSupport/vscode-R#1476] opened 2024-01-12 19:58 UTC
Type: <b>Bug</b>

Session crashes and integrated terminal killed when attempting to read in large Excel file with read_xlsx. Works with smaller Excel files. Additionally, able to read in same file with pd.read_csv in Python extension.

Reprex:
require(readxl)
\# Size_Test.xlsx a 390,514 row x 57 column spreadsheet filled with random numbers.
output = read_xlsx("./Size_Test.xlsx")
\# Crash occurs.

Extension version: 2.8.2
VS Code version: Code 1.85.1 (0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2, 2023-12-13T09:49:37.021Z)
OS version: Windows_NT x64 10.0.22621
Modes:
Remote OS version: Linux x64 5.15.133.1-microsoft-standard-WSL2

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (6.23GB free)|
|Process Argv|--folder-uri=vscode-remote://wsl+Ubuntu/home/bactkinson --remote=wsl+Ubuntu --crash-reporter-id 6c0104b0-bbfc-47de-bcdf-f98961bed201|
|Screen Reader|no|
|VM|0%|

|Item|Value|
|---|---|
|Remote|WSL: Ubuntu|
|OS|Linux x64 5.15.133.1-microsoft-standard-WSL2|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)|
|Memory (System)|7.61GB (5.76GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805cf:30301675
binariesv615:30325510
vsaa593:30376534
py29gd2263:30899288
vsclangdf:30486550
c4g48928:30535728
azure-dev_surveyone:30548225
2i9eh265:30646982
0bi6i642:30933247
pythongtdpath:30769146
i26e3531:30792625
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
pythontbext0:30879054
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
aa_t_chat:30882232

```

</details>

**Comment by eitsupi** [comment] 2024-01-13 01:12
Any reason to think this is a bug of vscode-R?
Does the crash not occur in terminals outside of vscode?

**Comment by bwactkinson** [comment] 2024-01-15 15:40
I'm able to execute the following Python code successfully (both within an interactive Jupyter session and by printing the output of test.head to the integrated terminal directly):

import pandas as pd

test = pd.read_excel("./Size_Test.xlsx")
/# print(test.head())

Additionally, I'm able to execute the same R code from within RStudio without any issues.

Hope that's helpful.

**Comment by eitsupi** [comment] 2024-01-15 16:07
Is RStudio on the same OS (i.e. WSL2)?
You need to see that behavior on R run on WSL2.
My guess is that this is most likely not a bug of vscode-R

**Comment by bwactkinson** [comment] 2024-01-15 23:42
You are correct. The problem was with how much memory my system was allocating towards running WSL 2. The problem was solved by consulting the instructions here: https://fizzylogic.nl/2023/01/05/how-to-configure-memory-limits-in-wsl2

Thanks for your help, appreciate it.

**Comment by KyleHaynes** [comment] 2024-01-16 00:06
@bwactkinson close the issue?

**Closed** 2024-01-16 00:16 UTC
