### ISSUE TITLE
Terminal issue

### ISSUE THREAD

**Issue by robhanssen** [REditorSupport/vscode-R#864] opened 2021-11-09 19:15 UTC
**Describe the bug**
Error when starting R-terminal

**To Reproduce**

run  R script

## Do you want to fix by self? (We hope your help!)

 No

## (If yes,) what kind of help do you want? (e.g. Which file should I fix, Survey (related documents)

error message:
Error identifying terminal! Please run command "Developer: Toggle Developer Tools", find the message starting with "[chooseTerminal]", and copy the message to https://github.com/REditorSupport/vscode-R/issues

[chooseTerminal] text
A. There are 5 terminals: Terminal 0: R Interactive Terminal 1: Rterm Terminal 2: Rterm Terminal 3: powershell Terminal 4: Rterm B. There are 5 terminals: Terminal 0: R Interactive Terminal 1: Rterm Terminal 2: Rterm Terminal 3: powershell Terminal 4: Rterm C. There are 5 terminals: Terminal 0: R Interactive Terminal 1: Rterm Terminal 2: Rterm Terminal 3: powershell Terminal 4: Rterm 

VSCode 1.62.1
R 4.1.0
Started today (Nov 9, 2021). No issues yesterday, no changes made.

**Comment by renkun-ken** [comment] 2021-11-10 00:01
Might be caused by the [latest release of VS Code 1.62.1](https://github.com/microsoft/vscode/releases/tag/1.62.1).

**Comment by juuzia** [comment] 2021-11-10 12:04
I've experienced the same issue today (yesterday was ok) having VSCode 1.62.1 release. 

[chooseTerminal] A. There are 2 terminals: Terminal 0: bash Terminal 1: R B. There are 2 terminals: Terminal 0: bash Terminal 1: R C. There are 2 terminals: Terminal 0: bash Terminal 1: R

**Comment by robhanssen** [comment] 2021-11-10 14:35
Don't if this helps, but I found that while typing the command ">R: create R terminal" in the VSCode Command Palette, there was already an R terminal open, and it was yellow. After killing this terminal, it worked as before - for as long as VSCode was open. After closing and restarting, the issue was still the same.

**Comment by renkun-ken** [comment] 2021-11-12 01:11
It should be fixed in [VS Code 1.62.2](https://github.com/microsoft/vscode/releases/tag/1.62.2).

**Comment by renkun-ken** [comment] 2021-11-15 10:07
Feel free to reopen if the problem still persists. Closing.

**Closed by renkun-ken** 2021-11-15 10:07 UTC
Labels: bug
