### ISSUE TITLE
Session-watcher plots not updating

### ISSUE THREAD

**Issue by FrederikFilip** [REditorSupport/vscode-R#1005] opened 2022-02-17 14:07 UTC
**Describe the bug**
Re-opening of this issue/bug: https://github.com/REditorSupport/vscode-R/issues/624
Session-watcher plots not updating.
Once the first plot is created, then no new plots are made.

**To Reproduce**
The most simple example would be the following R-code:

plot(1,1) --> the plot shows in sessionwathcer
points(1,1.2) --> the new point is **not** added to the plot

Or simply
plot(1,1) --> the plot shows in sessionwathcer
plot(1,2) --> the plotting window is **not** updating.

**Environment (please complete the following information):**

- OS: Linux (remote)
- VSCode Version: 1.64.2
- R Version: 3.4.4
- vscode-R version: 2.3.8

**Comment by renkun-ken** [comment] 2022-02-17 14:32
Duplicate of #986

**Closed by renkun-ken** 2022-02-17 14:32 UTC
Labels: bug
