### ISSUE TITLE
`r.lsp.diagnostics` setting does not work

### ISSUE THREAD

**Issue by qizhengyang2017** [REditorSupport/vscode-R#1196] opened 2022-09-13 03:39 UTC
I turned off the r.lsp.diagnostics, but the warnings didn't disappear.

**Screenshots**
<img width="290" alt="image" src="https://user-images.githubusercontent.com/27215125/189802220-7c2114b7-d6b3-4e65-8afe-30f406be2d56.png">

<img width="894" alt="image" src="https://user-images.githubusercontent.com/27215125/189801864-bd149aab-b342-479e-a428-70fc24f91759.png">

**Environment**
- OS: macOS
- VSCode Version:  1.71.0 (Universal)
- R Version: 4.0.5
- vscode-R version: 2.5.3

**Comment by ManuelHentschel** [comment] 2022-09-13 05:56
I have the same issue, see also https://github.com/REditorSupport/vscode-R/issues/1191#issuecomment-1242647516 ff.

As a workaround you can disable diagnostics by putting `options(languageserver.diagnostics = FALSE)` in your .Rprofile.

**Comment by renkun-ken** [comment] 2022-09-13 06:14
Cannot reproduce it on macOS and Linux. Maybe it is a Windows-specific issue regarding vscode-languageclient v8.0.2?

**Comment by ManuelHentschel** [comment] 2022-09-13 06:37
> Cannot reproduce it on macOS and Linux. Maybe it is a Windows-specific issue regarding vscode-languageclient v8.0.2?

That seems to be correct, downgrading to vscode-R v2.5.2 solves the issue for me.

**Comment by qizhengyang2017** [comment] 2022-09-13 06:47
How could I downgrade it? I clinck `Install another version..`, but no reaction. By the way, I used macOS and Linux, so it's probably not a Windows-specific issue.
<img width="681" alt="image" src="https://user-images.githubusercontent.com/27215125/189829905-a51b11cb-b064-4839-adad-3bd0677a9c8c.png">

**Comment by qizhengyang2017** [comment] 2022-09-13 06:51
Sorry, I see the pup-up box.

**Comment by renkun-ken** [comment] 2022-09-13 07:07
@ManuelHentschel @qizhengyang2017 Would you like to install the latest development version of languageserver, enable `r.lsp.debug` in vscode settings and take a look at the log of "R Language Server" channel in vscode output pane?

On languageserver startup, it should receive settings from vscode-R language client like the following:

```
[2022-09-13 15:03:14.759] settings  {
  "enabled": true,
  "args": [],
  "promptToInstall": true,
  "debug": true,
  "diagnostics": true,
  "lang": "",
  "use_stdio": false
}
```

If you disable `r.lsp.diagnostics`, languageserver should also receive a notification of changed configuration in the same format:

```
[2022-09-13 15:05:21.493] settings  {
  "enabled": true,
  "args": [],
  "promptToInstall": true,
  "debug": true,
  "diagnostics": false,
  "lang": "",
  "use_stdio": false
}
```

Could you confirm whether the languageserver shows such log?

**Comment by ManuelHentschel** [comment] 2022-09-14 07:42
With diagnostics enabled I get
```
[2022-09-14 09:33:25.154] settings  {
  "enabled": true,
  "args": [],
  "promptToInstall": true,
  "debug": true,
  "diagnostics": true,
  "lang": "",
  "use_stdio": false
}
```
With diagnostics disabled I get
```
[2022-09-14 09:32:22.208] settings  {
  "enabled": true,
  "args": [],
  "promptToInstall": true,
  "debug": true,
  "diagnostics": false,
  "lang": "",
  "use_stdio": false
}
```

In **both** cases I get the following linter message in an empty file:
<details>
<summary>Trailing blank lines are superfluous.</summary>
<pre>
[{
	"resource": "XXXXXX/temp/test.R",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 2,
	"message": "Trailing blank lines are superfluous.",
	"source": "trailing_blank_lines_linter",
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]
</pre>
</details>

<details><summary>(namespaces from the log)</summary>
<pre>
  "namespaces": {
    "processx": "3.5.2",
    "compiler": "4.1.0",
    "R6": "2.5.1",
    "graphics": "4.1.0",
    "parallel": "4.1.0",
    "tools": "4.1.0",
    "collections": "0.3.5",
    "utils": "4.1.0",
    "grDevices": "4.1.0",
    "stats": "4.1.0",
    "datasets": "4.1.0",
    "xml2": "1.3.2",
    "stringi": "1.7.5",
    "callr": "3.7.0",
    "methods": "4.1.0",
    "jsonlite": "1.7.3",
    "ps": "1.6.0",
    "base": "4.1.0",
    "languageserver": "0.3.13"
  },
</pre></details>

However, I can disable the linter using `options(languageserver.diagnostics = FALSE)`. This does not show up in the log (i.e. it still shows `"diagnostics": true`, but disables the linter.

**Comment by albert-ying** [comment] 2022-09-19 20:52
Same problem here for MacOS. Also, I'm wondering if there is a way to disable all styling linters but keep the syntax errors.

**Comment by kongdd** [comment] 2022-09-20 04:23
Even trough `r.lsp.diagnostics` has been disabled, in the workspace setting `r.lsp.diagnostics` default is true.

**Comment by dstmu** [comment] 2022-10-02 17:53
Same here on MacOS. v.2.5.3.

**Comment by renkun-ken** [comment] 2022-10-03 02:27
@ManuelHentschel From your languageserver log, it looks like it did receive `r.lsp.diagnostics: false` but it still publishes diagnostics on document open/save/modify?

**Comment by renkun-ken** [comment] 2022-10-03 02:30
> Same problem here for MacOS. Also, I'm wondering if there is a way to disable all styling linters but keep the syntax errors.

You could modify your global `~/.lintr` or workspace `{workspaceFolder}/.lintr` to specify linters to be used. If you want to get notified by parse-errors only, you might want to put the following in your lintr config:

```
linters: list()
```

**Comment by renkun-ken** [comment] 2022-10-03 02:32
> Even trough `r.lsp.diagnostics` has been disabled, in the workspace setting `r.lsp.diagnostics` default is true.

Do you mean VS Code workspace settings in `{workspaceFolder}/.vscode/settings.json`? If you don't have this file, then VS Code will follow the global settings.

**Comment by renkun-ken** [comment] 2022-10-03 02:33
> Same here on MacOS. v.2.5.3.

Would you like to confirm that languageserver does receive the settings update to disable diagnostics by taking a look at <https://github.com/REditorSupport/vscode-R/issues/1196#issuecomment-1244990357>?

**Comment by vsabarly** [comment] 2022-10-12 08:51
Hi, same issue on MacOS v2.6.0.

With the latest development version of languageserver, it seems that it does receive the setting:
- diagnostics enabled:
```
settings  {
  "enabled": true,
  "args": [],
  "promptToInstall": true,
  "debug": true,
  "diagnostics": true,
  "lang": "",
  "use_stdio": false
}
```

- disabled:
```
settings  {
  "enabled": true,
  "args": [],
  "promptToInstall": true,
  "debug": true,
  "diagnostics": false,
  "lang": "",
  "use_stdio": false
}
```
Actually unticking the "enable diagnostics" setting works but the diagnostics appear again when VS code is restarted (and I have to check / uncheck the setting again to make them disappear).

**Comment by mihaiconstantin** [comment] 2022-10-13 08:37
It seems related to https://github.com/REditorSupport/languageserver/issues/570. So far, I've been following @renkun-ken's suggestion in https://github.com/REditorSupport/vscode-R/issues/1196#issuecomment-1264852007 or using `v2.5.2` as workarounds.

**Comment by renkun-ken** [comment] 2022-10-13 09:33
Now I can reproduce the problem. Let me take a closer look. Looks like the diagnostics are triggered before the settings are received.

**Comment by renkun-ken** [comment] 2022-10-13 10:13
Should be fixed via https://github.com/REditorSupport/languageserver/pull/577.

**Comment by mihaiconstantin** [comment] 2022-10-13 10:55
Thanks, @renkun-ken! I checked via `remotes::install_github("renkun-ken/languageserver@drop-diagnostics")` and it works as expected!

**Comment by dstmu** [comment] 2022-10-13 17:27
Same here. `@drop-diagnostics` fixes the issue. Thank you!

**Closed** 2022-10-13 17:38 UTC
Labels: bug

**Comment by vsabarly** [comment] 2022-10-13 20:17
Thanks a lot!

**Comment by IvanGonzalezBRA** [comment] 2024-11-28 11:00
I had the same issue with lintr not going away after toggling "Enable LSP diagnostics"; it turns out that there was an error in my `settings.json` that was caused from an other custom setting.
In my case, somehow toggling the setting `terminal.integrated.enableMultiLinePasteWarning` from the settings UI had written an option `false` in .json file that is not recognized as a valid option.
After correcting the non-lintr related error; things work out perfectly now.
